416-form-objects/signup-before/config/routes.rb
Example::Application.routes.draw do
  resources :posts


  root to: 'users#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  resources :passwords
end

416-form-objects/signup-before/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body
end

416-form-objects/signup-before/app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

416-form-objects/signup-before/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_one :profile
end

416-form-objects/signup-before/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

416-form-objects/signup-before/app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  def new
    @password_form = PasswordForm.new(current_user)
  end

  def create
    @password_form = PasswordForm.new(current_user)
    if @password_form.submit(params[:password_form])
      redirect_to current_user, notice: "Successfully changed password."
    else
      render "new"
    end
  end

end

416-form-objects/signup-before/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def post_params
      params.require(:post).permit(:body)
    end
end

416-form-objects/signup-before/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

416-form-objects/signup-before/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @signup_form = SignupForm.new
  end

  def create
    @signup_form = SignupForm.new
    if @signup_form.submit(params[:user])
      user = @signup_form.user
      session[:user_id] = user.id
      redirect_to user, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def show
    @user = current_user
  end
end

416-form-objects/signup-before/app/helpers/sessions_helper.rb
module SessionsHelper
end

416-form-objects/signup-before/app/helpers/users_helper.rb
module UsersHelper
end

416-form-objects/signup-before/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Users</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% if current_user %>
        Logged in as <%= link_to current_user.username, user_path(current_user) %>.
        <%= link_to "Log Out", logout_path %>
      <% else %>
        <%= link_to "Sign Up", signup_path %> or
        <%= link_to "Log In", login_path %>
      <% end %>

      <% flash.each do |name, msg| %>
        <p><%= content_tag :div, msg, id: "flash_#{name}" %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

416-form-objects/signup-before/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

416-form-objects/signup-before/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

416-form-objects/signup-before/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.body %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

416-form-objects/signup-before/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

416-form-objects/signup-before/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

416-form-objects/signup-before/app/views/users/index.html.erb
<h1>Welcome</h1>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

416-form-objects/signup-before/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @signup_form, as: :user, url: users_path do |f| %>
  <% if @signup_form.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @signup_form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.check_box :subscribed %>
    <%= f.label :subscribed, "Subscribe to our mailing list." %>
  </div>

  <h3>Profile Details</h3>
  <div class="field">
    <%= f.label :twitter_name %><br />
    <%= f.text_field :twitter_name %>
  </div>
  <div class="field">
    <%= f.label :github_name %><br />
    <%= f.text_field :github_name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio, rows: 5, cols: 40 %>
  </div>

  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

416-form-objects/signup-before/app/views/users/show.html.erb
<h1>User Profile</h1>

<p>Username: <%= @user.username %></p>

<p>Email: <%= @user.email %></p>

<% if @user.profile.twitter_name.present? %>
  <p>Twitter: <%= @user.profile.twitter_name %></p>
<% end %>

<% if @user.profile.github_name.present? %>
  <p>GitHub: <%= @user.profile.github_name %></p>
<% end %>

<% if @user.profile.bio.present? %>
  <p>Bio: <%= @user.profile.bio %></p>
<% end %>

<p><%= link_to "Change Password", new_password_path %></p>